In [ ]:
SELECT COUNT(*) AS Antal
  FROM [AdventureWorks2019].[Person].[Person]